### ISSUE TITLE
Language Accuracy

### ISSUE THREAD

**Issue by noonkay** [CommerceDataService/midaas-api#11]
As a user I want the language on the website and each visualization to be precise and descriptive.

## Definition of Done
- [x] Front end code written

## Acceptance Criteria
 - [x] Under topics/gender, the wording describing the ratio  is correct.
 - [x] On the topic exploration page, there are no grammatical errors.

**Comment by arowla** [comment]
* Under topics/gender, the wording or the ratio displayed by state is reversed
* On the topic exploration page, there are some grammatical errors
