### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by noonkay** [CommerceDataService/midaas-api#8]
As a user I would like to receive precise and clear instructions on how to use the Midaas API.

## Definition of Done
- [ ] Front end code written

## Acceptance Criteria
- [ ] Can view the API path and end points 
- [ ] Can receive API keys from api.data.gov
- [ ] Can see query parameters for each end point
- [ ] Can view sample query and response
- [ ] Responses from the exposed API are consistent with the website front end

**Comment by arowla** [comment]
Let's talk to @bahadasx about helping with this task.
